### ISSUE TITLE
Validity of `const_ptr as *mut T` casts relies upon `Arc` implementation details

### ISSUE THREAD

**Issue by zetanumbers** [njaard/lending-cell#1]
If it was okay to make these casts, there would have been `Arc::as_mut_ptr`. Thankfully there ~are other associated functions~ is `UnsafeCell` you could rely upon.

**Comment by oskgo** [comment]
I don't think this is the case. You can freely convert between `*mut T` and `*const T` in safe rust as follows:

```rust
fn const_to_mut<T>(a: *const T) -> *mut T {
    a as *mut T
}
```

The other direction doesn't even need an explicit cast. See the following thread for more https://internals.rust-lang.org/t/what-is-the-real-difference-between-const-t-and-mut-t-raw-pointers/6127/17.

**Comment by zetanumbers** [comment]
> I don't think this is the case. You can freely convert between `*mut T` and `*const T` in safe rust

Ok, i didn't make this clear. It's generally okay to make these casts. However, you cannot write to the resulting pointer if it is not "tagged" appropriately for the writes, which would be an implementation detail. The point is, if it was okay to get a mutable pointer through a cast like this, there wouldn't have been a need for the cast in the first place, because it would have been an associated function (like `as_mut_ptr`).

**Comment by oskgo** [comment]
I've not heard this tagging terminology used with rust pointers. I'm struggling to find any resources on this, and I'm not convinced that the absence of a function proves that safe usage is impossible. My best guess is that you're saying that `Arc` could hypothetically contain something like a private `Option<&T>` field that is only populated whenever the reference count is above 1. This would make it unsafe to get mutable references from the `Arc` when the reference count is above 1. Is this what you're arguing? Wouldn't you then be able to get away with your own implementation of `Arc`, which would make sure that this implementation detail never changes?

Anyways, I've become convinced that `UnsafeCell` is necessary regardless of the implementation of `Arc`. The reason I'm convinced is that you can have a `&LendingCell` while you're modifying the underlying value in the `Arc` from the `BorrowedCell`. This will break the invariant that only values behind an `UnsafeCell` can change during the lifetime of a shared reference. Fixing this only requires `UnsafeCell` for `LendingCell` however.

**Comment by zetanumbers** [comment]
> This will break the invariant that only values behind an `UnsafeCell` can change during the lifetime of a shared reference

Oh, well, i guess was trying to give an overcomplicated explanation why this is wrong, even when MIRI doesn't fail.

About "pointer tagging" you can learn from [Stacked Borrows](https://plv.mpi-sws.org/rustbelt/stacked-borrows/) experimental proposal for aliasing memory model of Rust, which MIRI checks your code for. It helped me a lot to understand how to safely work with raw pointers in Rust.

**Comment by njaard** [comment]
I don't have easy keyboard access right now, but thanks for the information and review, I'll read through it all tomorrow
